image: marthym/latex:1.1.0
variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache: 
  paths:
    - build/
    
compile:
  stage: build
  script:
    - latexmk -f -r swr-class/latexmkrc || true
  artifacts:
    expire_in: 2 minute
    paths:
      - "build/dos-au-muur.pdf"

deploy-SNAPSHOT:
  stage: deploy
  variables:
    GIT_STRATEGY: clone
  script:
    - mv "build/dos-au-muur.pdf" "SWR-Dos au Muur.pdf"

  artifacts:
    expire_in: 1 week
    name: "SWR-Dos au Muur SNAPSHOT"
    paths:
      - "SWR-Dos au Muur.pdf"
  allow_failure: true

deploy-RELEASE:
  stage: deploy
  variables:
    GIT_STRATEGY: clone
  only:
    - tags
  script:
      - mv "build/dos-au-muur.pdf" "SWR-Dos au Muur v$CI_COMMIT_TAG.pdf"
  artifacts:
    name: "SWR-Dos au Muur v$CI_COMMIT_TAG"
    paths:
      - "SWR-Dos au Muur v$CI_COMMIT_TAG.pdf"