image: marthym/latex:1.0.0

dos-au-muur:
  stage: build
  script:
    - latexmk -f dos-au-muur/dos-au-muur.tex || true
    - mv "build/dos-au-muur.pdf" "SWR-Dos au Muur.pdf"
  artifacts:
    paths:
    - "SWR-Dos au Muur.pdf"
  allow_failure: true

songes-de-l-uhumele:
  stage: build
  script:
    - latexmk -f songes-de-l-uhumele/songes-de-l-uhumele.tex || true
    - mv "build/songes-de-l-uhumele.pdf" "SWR-Songes de l'Uhumele.pdf"

  artifacts:
    paths:
    - "SWR-Songes de l'Uhumele.pdf"
  allow_failure: true